# Generated by Django 4.2.11 on 2025-10-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidocs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequestlog',
            name='is_public_api',
            field=models.BooleanField(default=False, help_text='Is this endpoint publicly documented and exposed?'),
        ),
    ]
