# Generated by Django 5.2.8 on 2025-12-20 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apidocs', '0002_apirequestlog_is_public_api'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apirequestlog',
            old_name='ip_address',
            new_name='client_ip',
        ),
    ]
