# Generated by Django 4.2.11 on 2026-03-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamcentral', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['code'], name='department_code_idx'),
        ),
        migrations.AddIndex(
            model_name='employeetype',
            index=models.Index(fields=['code'], name='employee_type_code_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentstatus',
            index=models.Index(fields=['code'], name='employment_status_code_idx'),
        ),
        migrations.AddIndex(
            model_name='leaveapplication',
            index=models.Index(fields=['employee', 'status', 'start_date'], name='leave_application_idx'),
        ),
        migrations.AddIndex(
            model_name='leavebalance',
            index=models.Index(fields=['employee', 'leave_type', 'year'], name='leave_balance_idx'),
        ),
        migrations.AddIndex(
            model_name='leavetype',
            index=models.Index(fields=['code'], name='leave_type_code_idx'),
        ),
        migrations.AddIndex(
            model_name='memberprofile',
            index=models.Index(fields=['member_code'], name='member_code_idx'),
        ),
        migrations.AddIndex(
            model_name='memberprofile',
            index=models.Index(fields=['email'], name='member_email_idx'),
        ),
        migrations.AddIndex(
            model_name='memberprofile',
            index=models.Index(fields=['status'], name='member_status_idx'),
        ),
        migrations.AddIndex(
            model_name='memberprofile',
            index=models.Index(fields=['employee'], name='member_employee_idx'),
        ),
        migrations.AddIndex(
            model_name='memberstatus',
            index=models.Index(fields=['code'], name='member_status_code_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['code'], name='role_code_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['rank'], name='role_rank_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['department', 'name'], name='team_dept_name_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['leader'], name='team_leader_idx'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('owner',), name='one_active_address_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='leavebalance',
            constraint=models.UniqueConstraint(fields=('employee', 'leave_type', 'year'), name='unique_leave_balance'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('name', 'department'), name='unique_team_name_per_dept'),
        ),
    ]
