# Generated by Django 4.2.11 on 2025-10-06 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="ISIC code (e.g., 'A', '01', '011', '0111')", max_length=10, unique=True)),
                ('description', models.TextField(help_text="Description of the industry (e.g., 'Agriculture, forestry and fishing')")),
                ('level', models.CharField(choices=[('SECTION', 'Section'), ('DIVISION', 'Division'), ('GROUP', 'Group'), ('CLASS', 'Class')], help_text='Hierarchy level (Section, Division, Group, Class)', max_length=10)),
                ('sector', models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary'), ('TERTIARY', 'Tertiary')], help_text='Broader sector (e.g., Primary, Secondary, Tertiary)', max_length=20)),
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industries',
                'ordering': ['code'],
            },
        ),
    ]
