# Generated by Django 4.2.11 on 2025-10-06 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('industries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='industry',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='industry',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent industry (e.g., Division for a Group, Group for a Class)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='industries.industry'),
        ),
        migrations.AddField(
            model_name='industry',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='industry',
            index=models.Index(fields=['code'], name='industries__code_605d50_idx'),
        ),
        migrations.AddIndex(
            model_name='industry',
            index=models.Index(fields=['level'], name='industries__level_398e29_idx'),
        ),
        migrations.AddIndex(
            model_name='industry',
            index=models.Index(fields=['sector'], name='industries__sector_ee51ef_idx'),
        ),
        migrations.AddIndex(
            model_name='industry',
            index=models.Index(fields=['parent'], name='industries__parent__d48e59_idx'),
        ),
        migrations.AddIndex(
            model_name='industry',
            index=models.Index(fields=['created_by'], name='industries__created_c72b7e_idx'),
        ),
        migrations.AddIndex(
            model_name='industry',
            index=models.Index(fields=['updated_by'], name='industries__updated_458e58_idx'),
        ),
        migrations.AddIndex(
            model_name='industry',
            index=models.Index(fields=['deleted_by'], name='industries__deleted_bc5cc1_idx'),
        ),
    ]
