# Generated by Django 5.2.8 on 2025-11-24 12:45

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industries', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalIndustry',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('code', models.CharField(db_index=True, help_text="ISIC code (e.g., 'A', '01', '011', '0111')", max_length=10)),
                ('description', models.TextField(help_text="Description of the industry (e.g., 'Agriculture, forestry and fishing')")),
                ('level', models.CharField(choices=[('SECTION', 'Section'), ('DIVISION', 'Division'), ('GROUP', 'Group'), ('CLASS', 'Class')], help_text='Hierarchy level (Section, Division, Group, Class)', max_length=10)),
                ('sector', models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary'), ('TERTIARY', 'Tertiary')], help_text='Broader sector (e.g., Primary, Secondary, Tertiary)', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this object.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who deleted this object.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, help_text='Parent industry (e.g., Division for a Group, Group for a Class)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='industries.industry')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Industry',
                'verbose_name_plural': 'historical Industries',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
