# Generated by Django 4.2.11 on 2025-06-18 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('location_type', models.CharField(choices=[('country', 'Country'), ('state', 'State'), ('city', 'City')], max_length=10)),
                ('name', models.CharField(max_length=128)),
                ('code', django_countries.fields.CountryField(max_length=2, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GlobalRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('East Asia & Pacific', 'East Asia & Pacific'), ('Europe & Central Asia', 'Europe & Central Asia'), ('Latin America & the Caribbean', 'Latin America & the Caribbean'), ('Middle East & North Africa', 'Middle East & North Africa'), ('South Asia', 'South Asia'), ('Sub-Saharan Africa', 'Sub-Saharan Africa'), ('North America', 'North America')], max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Global Region',
                'verbose_name_plural': 'Global Regions',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('location_type', models.CharField(choices=[('country', 'Country'), ('state', 'State'), ('city', 'City')], max_length=10)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(max_length=128)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'ordering': ['id'],
                'unique_together': {('country', 'name')},
            },
        ),
        migrations.AddField(
            model_name='country',
            name='global_region',
            field=models.ForeignKey(help_text='e.g., South-East Asia, North America', on_delete=django.db.models.deletion.PROTECT, to='locations.globalregion'),
        ),
        migrations.AddField(
            model_name='country',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('location_type', models.CharField(choices=[('country', 'Country'), ('state', 'State'), ('city', 'City')], max_length=10)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(max_length=128)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.state')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['country', 'name'], name='locations_c_country_a5360f_idx'), models.Index(fields=['postal_code'], name='locations_c_postal__e04e88_idx')],
                'unique_together': {('country', 'state', 'name')},
            },
        ),
    ]
