# Generated by Django 4.2.11 on 2025-11-13 14:08

from django.conf import settings
import django.contrib.postgres.indexes
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import locations.models.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCustomCity',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Name of the city', max_length=200)),
                ('asciiname', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('geoname_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(blank=True, help_text="Numeric administrative code for level 3 (e.g., '4285' for Hatkanangale)", max_length=20, null=True)),
                ('latitude', models.FloatField(blank=True, help_text="Latitude of the city's central point (optional)", null=True)),
                ('longitude', models.FloatField(blank=True, help_text="Longitude of the city's central point (optional)", null=True)),
                ('location_source', models.CharField(blank=True, help_text="Source of the city data (e.g., 'geonames', 'GOI')", max_length=50, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical City',
                'verbose_name_plural': 'historical Cities',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCustomCountry',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('geoname_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('asciiname', models.CharField(blank=True, max_length=100, null=True)),
                ('alternatenames', models.TextField(blank=True, help_text='Comma-separated list of alternate names', null=True)),
                ('country_code', models.CharField(blank=True, help_text='ISO-3166 2-letter country code', max_length=2, null=True)),
                ('country_capital', models.CharField(blank=True, help_text='Capital city of the country', max_length=100, null=True)),
                ('currency_symbol', models.CharField(blank=True, help_text='Currency symbol (e.g., ₹)', max_length=10, null=True)),
                ('currency_code', models.CharField(blank=True, help_text='ISO 4217 currency code (e.g., INR)', max_length=3, null=True)),
                ('currency_name', models.CharField(blank=True, help_text='Currency name (e.g., Indian Rupee)', max_length=50, null=True)),
                ('country_phone_code', models.CharField(blank=True, help_text='Country phone code (e.g., +91)', max_length=10, null=True)),
                ('postal_code_regex', models.CharField(blank=True, help_text='Regex for postal code validation', max_length=300, null=True)),
                ('country_languages', models.TextField(blank=True, help_text='Comma-separated list of language codes (e.g., hi,en)', max_length=300, null=True)),
                ('population', models.BigIntegerField(blank=True, help_text='Country population', null=True)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('has_postal_code', models.BooleanField(default=True)),
                ('postal_code_length', models.CharField(blank=True, help_text='Maximum postal code length allowed for given country', max_length=20, null=True)),
                ('phone_number_length', models.CharField(blank=True, help_text='Maximum phone number length allowed for given country', max_length=20, null=True)),
                ('admin_codes', models.JSONField(blank=True, help_text="JSON object storing admin codes, e.g., {'admin1_codes': ['13', '14'], 'admin2_codes': ['594'], ...}", null=True)),
                ('location_source', models.CharField(blank=True, help_text="Source of the country data (e.g., 'geonames', 'GOI')", max_length=50, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Country',
                'verbose_name_plural': 'historical Countries',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCustomRegion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text="Name of the region (e.g., 'Kerala' for admin1_code '13')", max_length=200)),
                ('asciiname', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, help_text="Numeric administrative code for level 1 (e.g., '13' for Kerala)", max_length=20, null=True)),
                ('geoname_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('location_source', models.CharField(blank=True, help_text="Source of country's region data (e.g., 'geonames', 'GOI')", max_length=50, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Region/State',
                'verbose_name_plural': 'historical Regions/States',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCustomSubRegion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text="Name of the subregion (e.g., 'Kolhapur' for admin2_code '594')", max_length=200)),
                ('asciiname', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, help_text="Numeric administrative code for level 2 (e.g., '594' for Kolhapur)", max_length=20, null=True)),
                ('geoname_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('location_source', models.CharField(blank=True, help_text="Source of country's subregion data (e.g., 'geonames', 'GOI')", max_length=50, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Subregion/District',
                'verbose_name_plural': 'historical Subregions/Districts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalGlobalRegion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('asciiname', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('geoname_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('location_source', models.CharField(blank=True, help_text="Source of the global region data (e.g., 'geonames', 'GOI')", max_length=50, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Global Region',
                'verbose_name_plural': 'historical Global Regions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLocation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(blank=True, help_text="Numeric administrative code for level 4 (e.g., '1234' for a locality)", max_length=20, null=True)),
                ('postal_code', models.CharField(blank=True, help_text='Postal code (e.g., Indian PIN code for India)', max_length=20, null=True)),
                ('street_address', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.FloatField(blank=True, help_text='Latitude of the location (optional)', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Longitude of the location (optional)', null=True)),
                ('location_source', models.CharField(blank=True, help_text="Source of the location data (e.g., 'geonames', 'GOI')", max_length=50, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Location',
                'verbose_name_plural': 'historical Locations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTimezone',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('timezone_id', models.CharField(db_index=True, help_text="IANA Time Zone ID (e.g., 'Asia/Kolkata')", max_length=100, validators=[locations.models.timezone.validate_timezone_id])),
                ('gmt_offset_jan', models.DecimalField(decimal_places=1, help_text='GMT offset in January (hours, e.g., 5.5)', max_digits=4, validators=[locations.models.timezone.validate_offset])),
                ('dst_offset_jul', models.DecimalField(decimal_places=1, help_text='DST offset in July (hours, e.g., 5.5)', max_digits=4, validators=[locations.models.timezone.validate_offset])),
                ('raw_offset', models.DecimalField(decimal_places=1, help_text='Standard time offset without DST (hours, e.g., 5.5)', max_digits=4, validators=[locations.models.timezone.validate_offset])),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the timezone is currently in use')),
                ('display_name', models.CharField(help_text="Human-readable timezone name (e.g., 'India Standard Time')", max_length=150)),
                ('country_code', models.CharField(blank=True, help_text="ISO 3166-1 alpha-2 country code from CustomCountry (e.g., 'IN' for India)", max_length=2, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', 'Country code must be two uppercase letters.'), locations.models.timezone.validate_country_code])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Timezone',
                'verbose_name_plural': 'historical Timezones',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='customcity',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customcity',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customcity',
            name='subregion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='locations.customsubregion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customcity',
            name='timezone',
            field=models.ForeignKey(blank=True, db_column='timezone_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='locations.timezone', to_field='timezone_id'),
        ),
        migrations.AddField(
            model_name='customcity',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customcountry',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customcountry',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customcountry',
            name='global_regions',
            field=models.ManyToManyField(blank=True, related_name='countries', to='locations.globalregion'),
        ),
        migrations.AddField(
            model_name='customcountry',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customregion',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='locations.customcountry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customregion',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customregion',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customregion',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customsubregion',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customsubregion',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customsubregion',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subregions', to='locations.customregion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customsubregion',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='globalregion',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='globalregion',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='globalregion',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='locations.customcity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timezone',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timezone',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timezone',
            name='id',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timezone',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timezone',
            name='timezone_id',
            field=models.CharField(help_text="IANA Time Zone ID (e.g., 'Asia/Kolkata')", max_length=100, unique=True, validators=[locations.models.timezone.validate_timezone_id]),
        ),
        migrations.AlterUniqueTogether(
            name='customcity',
            unique_together={('name', 'subregion')},
        ),
        migrations.AlterUniqueTogether(
            name='customregion',
            unique_together={('name', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='customsubregion',
            unique_together={('name', 'region')},
        ),
        migrations.AddIndex(
            model_name='customcity',
            index=models.Index(fields=['geoname_id'], name='locations_c_geoname_147789_idx'),
        ),
        migrations.AddIndex(
            model_name='customcity',
            index=models.Index(fields=['name', 'subregion'], name='locations_c_name_c263e0_idx'),
        ),
        migrations.AddIndex(
            model_name='customcity',
            index=models.Index(fields=['latitude', 'longitude'], name='locations_c_latitud_b68080_idx'),
        ),
        migrations.AddIndex(
            model_name='customcity',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='custom_city_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='customcity',
            index=django.contrib.postgres.indexes.GinIndex(fields=['asciiname'], name='custom_city_asciiname_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='customcity',
            index=django.contrib.postgres.indexes.GinIndex(fields=['location_source'], name='custom_city_loc_src_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='customcountry',
            index=models.Index(fields=['geoname_id'], name='locations_c_geoname_7e3a0a_idx'),
        ),
        migrations.AddIndex(
            model_name='customcountry',
            index=models.Index(fields=['name', 'slug', 'geoname_id', 'country_code'], name='locations_c_name_ce01f1_idx'),
        ),
        migrations.AddIndex(
            model_name='customcountry',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='country_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='customcountry',
            index=django.contrib.postgres.indexes.GinIndex(fields=['asciiname'], name='country_asciiname_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='customcountry',
            index=django.contrib.postgres.indexes.GinIndex(fields=['alternatenames'], name='country_alternatename_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='customcountry',
            index=django.contrib.postgres.indexes.GinIndex(fields=['location_source'], name='country_loc_src_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='customregion',
            index=models.Index(fields=['geoname_id'], name='locations_c_geoname_fe5511_idx'),
        ),
        migrations.AddIndex(
            model_name='customregion',
            index=models.Index(fields=['code'], name='locations_c_code_2fbd08_idx'),
        ),
        migrations.AddIndex(
            model_name='customregion',
            index=models.Index(fields=['name', 'country', 'slug', 'geoname_id'], name='locations_c_name_9837ab_idx'),
        ),
        migrations.AddIndex(
            model_name='customregion',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='region_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='customregion',
            index=django.contrib.postgres.indexes.GinIndex(fields=['asciiname'], name='region_asciiname_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='customregion',
            index=django.contrib.postgres.indexes.GinIndex(fields=['location_source'], name='region_loc_src_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='customsubregion',
            index=models.Index(fields=['geoname_id'], name='locations_c_geoname_42bffe_idx'),
        ),
        migrations.AddIndex(
            model_name='customsubregion',
            index=models.Index(fields=['code'], name='locations_c_code_f7370f_idx'),
        ),
        migrations.AddIndex(
            model_name='customsubregion',
            index=models.Index(fields=['name', 'region', 'slug', 'geoname_id'], name='locations_c_name_1864ef_idx'),
        ),
        migrations.AddIndex(
            model_name='customsubregion',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='subregion_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='customsubregion',
            index=django.contrib.postgres.indexes.GinIndex(fields=['asciiname'], name='subregion_asciiname_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='customsubregion',
            index=django.contrib.postgres.indexes.GinIndex(fields=['location_source'], name='subregion_loc_src_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='globalregion',
            index=models.Index(fields=['name', 'slug'], name='locations_g_name_d76777_idx'),
        ),
        migrations.AddIndex(
            model_name='globalregion',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='global_region_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='globalregion',
            index=django.contrib.postgres.indexes.GinIndex(fields=['asciiname'], name='global_regn_asciiname_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='globalregion',
            index=models.Index(fields=['geoname_id'], name='global_region_geoname_id_idx'),
        ),
        migrations.AddIndex(
            model_name='globalregion',
            index=django.contrib.postgres.indexes.GinIndex(fields=['location_source'], name='global_region_loc_src_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['city', 'postal_code'], name='locations_l_city_id_3805f9_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['latitude', 'longitude'], name='locations_l_latitud_739c67_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=django.contrib.postgres.indexes.GinIndex(fields=['postal_code'], name='location_postal_code_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='location',
            index=django.contrib.postgres.indexes.GinIndex(fields=['street_address'], name='loc_street_address_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='location',
            index=django.contrib.postgres.indexes.GinIndex(fields=['location_source'], name='location_loc_src_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='timezone',
            index=models.Index(fields=['is_active'], name='locations_t_is_acti_1079f5_idx'),
        ),
        migrations.AddIndex(
            model_name='timezone',
            index=models.Index(fields=['country_code'], name='locations_t_country_31cd7c_idx'),
        ),
        migrations.AddConstraint(
            model_name='customcity',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name', 'subregion'), name='unique_active_city_name_subregion'),
        ),
        migrations.AddConstraint(
            model_name='customcity',
            constraint=models.CheckConstraint(check=models.Q(('latitude__gte', -90.0), ('latitude__lte', 90.0)), name='valid_latitude'),
        ),
        migrations.AddConstraint(
            model_name='customcity',
            constraint=models.CheckConstraint(check=models.Q(('longitude__gte', -180.0), ('longitude__lte', 180.0)), name='valid_longitude'),
        ),
        migrations.AddConstraint(
            model_name='customcountry',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_active_country_name'),
        ),
        migrations.AddConstraint(
            model_name='customcountry',
            constraint=models.CheckConstraint(check=models.Q(('population__gte', 0)), name='non_negative_population'),
        ),
        migrations.AddConstraint(
            model_name='customregion',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name', 'country'), name='unique_active_region_name_country'),
        ),
        migrations.AddConstraint(
            model_name='customsubregion',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name', 'region'), name='unique_active_subregion_name_region'),
        ),
        migrations.AddConstraint(
            model_name='globalregion',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_active_global_region_name'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('city', 'postal_code'), name='unique_active_location_city_postal_code'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(check=models.Q(('latitude__gte', -90.0), ('latitude__lte', 90.0)), name='location_valid_latitude'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(check=models.Q(('longitude__gte', -180.0), ('longitude__lte', 180.0)), name='location_valid_longitude'),
        ),
        migrations.AddField(
            model_name='historicaltimezone',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this object.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltimezone',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who deleted this object.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltimezone',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltimezone',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicallocation',
            name='city',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='locations.customcity'),
        ),
        migrations.AddField(
            model_name='historicallocation',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this object.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicallocation',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who deleted this object.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicallocation',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicallocation',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalglobalregion',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this object.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalglobalregion',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who deleted this object.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalglobalregion',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalglobalregion',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcustomsubregion',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this object.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcustomsubregion',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who deleted this object.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcustomsubregion',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcustomsubregion',
            name='region',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='locations.customregion'),
        ),
        migrations.AddField(
            model_name='historicalcustomsubregion',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcustomregion',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='locations.customcountry'),
        ),
        migrations.AddField(
            model_name='historicalcustomregion',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this object.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcustomregion',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who deleted this object.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcustomregion',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcustomregion',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcustomcountry',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this object.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcustomcountry',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who deleted this object.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcustomcountry',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcustomcountry',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcustomcity',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this object.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcustomcity',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who deleted this object.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcustomcity',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcustomcity',
            name='subregion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='locations.customsubregion'),
        ),
        migrations.AddField(
            model_name='historicalcustomcity',
            name='timezone',
            field=models.ForeignKey(blank=True, db_column='timezone_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='locations.timezone', to_field='timezone_id'),
        ),
        migrations.AddField(
            model_name='historicalcustomcity',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
