# Generated by Django 4.2.11 on 2025-06-09 16:51

from django.db import migrations
import random

def populate_locations(apps, schema_editor):
    GlobalRegion = apps.get_model('locations', 'GlobalRegion')
    Country = apps.get_model('locations', 'Country')
    State = apps.get_model('locations', 'State')
    City = apps.get_model('locations', 'City')

    # Regions data
    regions_data = [
        'East Asia & Pacific', 'Europe & Central Asia', 'Latin America & the Caribbean',
        'Middle East & North Africa', 'South Asia', 'Sub-Saharan Africa', 'North America'
    ]
    regions = {}
    for name in regions_data:
        region, _ = GlobalRegion.objects.get_or_create(name=name)
        regions[name] = region

    # Country, State, and City data
    country_data = [
        {'code': 'IN', 'name': 'India', 'region': 'South Asia', 'states': [
            {'name': 'Maharashtra', 'code': 'MH', 'cities': ['Mumbai', 'Pune', 'Nagpur']},
            {'name': 'Karnataka', 'code': 'KA', 'cities': ['Bangalore', 'Mysore']},
            {'name': 'Delhi', 'code': 'DL', 'cities': ['Delhi']},
            {'name': 'Gujarat', 'code': 'GJ', 'cities': ['Ahmedabad']},
            {'name': 'Tamil Nadu', 'code': 'TN', 'cities': ['Chennai']},
            {'name': 'West Bengal', 'code': 'WB', 'cities': ['Kolkata']},
            {'name': 'Haryana', 'code': 'HR', 'cities': ['Gurgaon']}
        ]},
        {'code': 'JP', 'name': 'Japan', 'region': 'East Asia & Pacific', 'states': [
            {'name': 'Aichi', 'code': 'AI', 'cities': ['Toyota City', 'Nagoya']},
            {'name': 'Tokyo', 'code': 'TK', 'cities': ['Tokyo']},
            {'name': 'Kyoto', 'code': 'KY', 'cities': ['Kyoto']},
            {'name': 'Osaka', 'code': 'OS', 'cities': ['Osaka']}
        ]},
        {'code': 'KR', 'name': 'South Korea', 'region': 'East Asia & Pacific', 'states': [
            {'name': 'Gyeonggi', 'code': 'GG', 'cities': ['Suwon', 'Seongnam']},
            {'name': 'Seoul', 'code': 'SL', 'cities': ['Seoul']},
            {'name': 'Jeju', 'code': 'JJ', 'cities': ['Jeju']},
            {'name': 'Gyeongsangnam', 'code': 'GN', 'cities': ['Pohang']}
        ]},
        {'code': 'DE', 'name': 'Germany', 'region': 'Europe & Central Asia', 'states': [
            {'name': 'Bavaria', 'code': 'BY', 'cities': ['Munich']},
            {'name': 'Lower Saxony', 'code': 'NI', 'cities': ['Wolfsburg']},
            {'name': 'Berlin', 'code': 'BE', 'cities': ['Berlin']},
            {'name': 'Baden-Württemberg', 'code': 'BW', 'cities': ['Walldorf']}
        ]},
        {'code': 'FR', 'name': 'France', 'region': 'Europe & Central Asia', 'states': [
            {'name': 'Île-de-France', 'code': 'IDF', 'cities': ['Paris']},
            {'name': 'Occitanie', 'code': 'OC', 'cities': ['Toulouse']}
        ]},
        {'code': 'GB', 'name': 'United Kingdom', 'region': 'Europe & Central Asia', 'states': [
            {'name': 'England', 'code': 'EN', 'cities': ['London', 'Cambridge']}
        ]},
        {'code': 'CH', 'name': 'Switzerland', 'region': 'Europe & Central Asia', 'states': [
            {'name': 'Vaud', 'code': 'VD', 'cities': ['Vevey']},
            {'name': 'Basel-Stadt', 'code': 'BS', 'cities': ['Basel']}
        ]},
        {'code': 'NL', 'name': 'Netherlands', 'region': 'Europe & Central Asia', 'states': [
            {'name': 'North Holland', 'code': 'NH', 'cities': ['Amsterdam', 'Delft']}
        ]},
        {'code': 'SE', 'name': 'Sweden', 'region': 'Europe & Central Asia', 'states': [
            {'name': 'Stockholm', 'code': 'ST', 'cities': ['Stockholm']}
        ]}
    ]

    # Populate Countries, States, and Cities
    for country_info in country_data:
        country, _ = Country.objects.get_or_create(
            code=country_info['code'],
            defaults={'name': country_info['name'], 'global_region': regions[country_info['region']]}
        )
        for state_info in country_info['states']:
            state, _ = State.objects.get_or_create(
                country=country, code=state_info['code'],
                defaults={'name': state_info['name']}
            )
            for city_name in state_info['cities']:
                City.objects.get_or_create(
                    country=country, city=city_name,
                    defaults={'state': state, 'postal_code': f"{country_info['code']}-{random.randint(1000, 9999)}"}
                )

class Migration(migrations.Migration):
    dependencies = [
        ('locations', '0001_initial'),        
    ]
    operations = [
        migrations.RunPython(populate_locations),
    ]