# Generated by Django 4.2.11 on 2025-11-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_full_current_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcountry',
            name='name',
            field=models.CharField(help_text='Name of the country', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customregion',
            name='code',
            field=models.CharField(blank=True, help_text="Numeric administrative code for level 1 (e.g., '13' for Kerala)", max_length=20, null=True, verbose_name='Administrative Code'),
        ),
        migrations.AlterField(
            model_name='historicalcustomcountry',
            name='name',
            field=models.CharField(db_index=True, help_text='Name of the country', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcustomregion',
            name='code',
            field=models.CharField(blank=True, help_text="Numeric administrative code for level 1 (e.g., '13' for Kerala)", max_length=20, null=True, verbose_name='Administrative Code'),
        ),
    ]
