# Generated by Django 4.2.11 on 2025-06-13 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('current_org_joining_day', models.DateField(blank=True, null=True)),
                ('current_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_in_country', to='locations.country')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Client Dashboard',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(default='uncategorized', max_length=128)),
                ('global_region', models.ForeignKey(help_text='Select the global region to which this industry belongs.', on_delete=django.db.models.deletion.PROTECT, related_name='industries', to='locations.globalregion')),
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industries',
                'ordering': ['id'],
                'unique_together': {('name', 'global_region')},
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(default='uncategorized', max_length=255)),
                ('cities', models.ManyToManyField(blank=True, help_text='List of cities where this organization has offices (including head office).', related_name='organizations_with_offices', to='locations.city')),
                ('headquarter_city', models.ForeignKey(help_text="The city where the organization's head office is located.", on_delete=django.db.models.deletion.PROTECT, related_name='headquarter_city_of_organization', to='locations.city')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.industry')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ClientOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('corporate_affiliation_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.city')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.organization')),
            ],
            options={
                'verbose_name': 'Corporate Affiliation',
                'verbose_name_plural': 'Corporate Affiliations',
                'unique_together': {('client', 'organization', 'from_date')},
            },
        ),
        migrations.AddField(
            model_name='client',
            name='current_industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_industry', to='clients.industry'),
        ),
        migrations.AddField(
            model_name='client',
            name='current_org_city',
            field=models.ForeignKey(blank=True, help_text='The city where the client is currently working or has worked for the organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_working_in_this_city', to='locations.city'),
        ),
        migrations.AddField(
            model_name='client',
            name='current_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_organization', to='clients.organization'),
        ),
        migrations.AddField(
            model_name='client',
            name='current_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_in_region', to='locations.globalregion'),
        ),
        migrations.AddField(
            model_name='client',
            name='current_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_in_state', to='locations.state'),
        ),
        migrations.AddField(
            model_name='client',
            name='other_organizations',
            field=models.ManyToManyField(blank=True, related_name='other_organizations', through='clients.ClientOrganization', to='clients.organization'),
        ),
    ]
