# Generated by Django 4.2.11 on 2025-06-09 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('current_org_joining_day', models.DateField(blank=True, null=True)),
                ('current_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='locations.country')),
                ('current_org_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.city')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Client Dashboard',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='uncategorized', max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industries',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='uncategorized', max_length=255)),
                ('current_org_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_current_city', to='locations.city')),
                ('current_org_head_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_current_head_office', to='locations.city')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.industry')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organization Dashboard',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ClientOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('corporate_affiliation_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.city')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.organization')),
            ],
            options={
                'verbose_name': 'Corporate Affiliation',
                'verbose_name_plural': 'Corporate Affiliations',
                'unique_together': {('client', 'organization', 'from_date')},
            },
        ),
        migrations.AddField(
            model_name='client',
            name='current_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_current_organization', to='clients.organization'),
        ),
        migrations.AddField(
            model_name='client',
            name='current_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='locations.globalregion'),
        ),
        migrations.AddField(
            model_name='client',
            name='current_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='locations.state'),
        ),
        migrations.AddField(
            model_name='client',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.industry'),
        ),
        migrations.AddField(
            model_name='client',
            name='other_orgs',
            field=models.ManyToManyField(blank=True, related_name='other_organizations', through='clients.ClientOrganization', to='clients.organization'),
        ),
    ]
