# Generated by Django 4.2.11 on 2025-06-09 16:55

from django.db import migrations
import random

def populate_clients(apps, schema_editor):
    Industry = apps.get_model('clients', 'Industry')
    Organization = apps.get_model('clients', 'Organization')
    Client = apps.get_model('clients', 'Client')
    City = apps.get_model('locations', 'City')
    Country = apps.get_model('locations', 'Country')
    State = apps.get_model('locations', 'State')
    GlobalRegion = apps.get_model('locations', 'GlobalRegion')

    # Industry data
    industry_names = [
        'Aerospace', 'Automotive', 'Biotechnology', 'Chemicals', 'Construction',
        'Consumer Electronics', 'Education', 'Energy', 'Entertainment', 'Fashion',
        'Finance', 'Food & Beverage', 'Healthcare', 'Hospitality', 'Information Technology',
        'Insurance', 'Logistics', 'Manufacturing', 'Media', 'Mining',
        'Pharmaceuticals', 'Real Estate', 'Retail', 'Telecommunications', 'Transportation',
        'Agriculture', 'Renewable Energy', 'Defense', 'E-commerce', 'Environmental Services'
    ]
    industries = {}
    for name in industry_names:
        industry, _ = Industry.objects.get_or_create(name=name)
        industries[name] = industry

    # Organization data
    organization_data = [
        {'name': 'Tata Consultancy Services', 'industry': 'Information Technology', 'head_office': 'Mumbai'},
        {'name': 'Reliance Industries', 'industry': 'Energy', 'head_office': 'Mumbai'},
        {'name': 'Infosys', 'industry': 'Information Technology', 'head_office': 'Bangalore'},
        {'name': 'HDFC Bank', 'industry': 'Finance', 'head_office': 'Mumbai'},
        {'name': 'Hindustan Unilever', 'industry': 'Consumer Electronics', 'head_office': 'Mumbai'},
        {'name': 'Bharti Airtel', 'industry': 'Telecommunications', 'head_office': 'Delhi'},
        {'name': 'Maruti Suzuki', 'industry': 'Automotive', 'head_office': 'Gurgaon'},
        {'name': 'Larsen & Toubro', 'industry': 'Construction', 'head_office': 'Mumbai'},
        {'name': 'Biocon', 'industry': 'Biotechnology', 'head_office': 'Bangalore'},
        {'name': 'Adani Green Energy', 'industry': 'Renewable Energy', 'head_office': 'Ahmedabad'},
        {'name': 'Zomato', 'industry': 'E-commerce', 'head_office': 'Gurgaon'},
        {'name': 'Sun Pharma', 'industry': 'Pharmaceuticals', 'head_office': 'Mumbai'},
        {'name': 'Asian Paints', 'industry': 'Chemicals', 'head_office': 'Mumbai'},
        {'name': 'Apollo Hospitals', 'industry': 'Healthcare', 'head_office': 'Chennai'},
        {'name': 'ITC Limited', 'industry': 'Food & Beverage', 'head_office': 'Kolkata'},
        {'name': 'Toyota Motor Corporation', 'industry': 'Automotive', 'head_office': 'Toyota City'},
        {'name': 'Sony Corporation', 'industry': 'Consumer Electronics', 'head_office': 'Tokyo'},
        {'name': 'Mitsubishi UFJ Financial', 'industry': 'Finance', 'head_office': 'Tokyo'},
        {'name': 'SoftBank Group', 'industry': 'Telecommunications', 'head_office': 'Tokyo'},
        {'name': 'Honda Motor Co.', 'industry': 'Automotive', 'head_office': 'Tokyo'},
        {'name': 'Nintendo', 'industry': 'Entertainment', 'head_office': 'Kyoto'},
        {'name': 'Panasonic', 'industry': 'Consumer Electronics', 'head_office': 'Osaka'},
        {'name': 'Mitsui & Co.', 'industry': 'Logistics', 'head_office': 'Tokyo'},
        {'name': 'Takeda Pharmaceutical', 'industry': 'Pharmaceuticals', 'head_office': 'Tokyo'},
        {'name': 'Sumitomo Corporation', 'industry': 'Manufacturing', 'head_office': 'Tokyo'},
        {'name': 'Rakuten', 'industry': 'E-commerce', 'head_office': 'Tokyo'},
        {'name': 'Japan Airlines', 'industry': 'Transportation', 'head_office': 'Tokyo'},
        {'name': 'NTT Corporation', 'industry': 'Telecommunications', 'head_office': 'Tokyo'},
        {'name': 'Asahi Group', 'industry': 'Food & Beverage', 'head_office': 'Tokyo'},
        {'name': 'Hitachi', 'industry': 'Information Technology', 'head_office': 'Tokyo'},
        {'name': 'Samsung Electronics', 'industry': 'Consumer Electronics', 'head_office': 'Suwon'},
        {'name': 'Hyundai Motor Company', 'industry': 'Automotive', 'head_office': 'Seoul'},
        {'name': 'SK Hynix', 'industry': 'Manufacturing', 'head_office': 'Seoul'},
        {'name': 'LG Electronics', 'industry': 'Consumer Electronics', 'head_office': 'Seoul'},
        {'name': 'POSCO', 'industry': 'Manufacturing', 'head_office': 'Pohang'},
        {'name': 'Korea Electric Power', 'industry': 'Energy', 'head_office': 'Seoul'},
        {'name': 'Kia Corporation', 'industry': 'Automotive', 'head_office': 'Seoul'},
        {'name': 'Shinhan Financial', 'industry': 'Finance', 'head_office': 'Seoul'},
        {'name': 'Naver Corporation', 'industry': 'Information Technology', 'head_office': 'Seongnam'},
        {'name': 'Kakao', 'industry': 'Information Technology', 'head_office': 'Jeju'},
        {'name': 'CJ Corporation', 'industry': 'Food & Beverage', 'head_office': 'Seoul'},
        {'name': 'Hana Financial', 'industry': 'Finance', 'head_office': 'Seoul'},
        {'name': 'Amorepacific', 'industry': 'Fashion', 'head_office': 'Seoul'},
        {'name': 'Korean Air', 'industry': 'Transportation', 'head_office': 'Seoul'},
        {'name': 'Lotte Chemical', 'industry': 'Chemicals', 'head_office': 'Seoul'},
        {'name': 'Volkswagen Group', 'industry': 'Automotive', 'head_office': 'Wolfsburg'},
        {'name': 'Siemens', 'industry': 'Manufacturing', 'head_office': 'Munich'},
        {'name': 'BNP Paribas', 'industry': 'Finance', 'head_office': 'Paris'},
        {'name': 'Unilever', 'industry': 'Consumer Electronics', 'head_office': 'London'},
        {'name': 'Nestlé', 'industry': 'Food & Beverage', 'head_office': 'Vevey'},
        {'name': 'SAP', 'industry': 'Information Technology', 'head_office': 'Walldorf'},
        {'name': 'Shell', 'industry': 'Energy', 'head_office': 'London'},
        {'name': 'Airbus', 'industry': 'Aerospace', 'head_office': 'Toulouse'},
        {'name': 'LVMH', 'industry': 'Fashion', 'head_office': 'Paris'},
        {'name': 'AstraZeneca', 'industry': 'Pharmaceuticals', 'head_office': 'Cambridge'},
        {'name': 'ING Group', 'industry': 'Finance', 'head_office': 'Amsterdam'},
        {'name': 'Ericsson', 'industry': 'Telecommunications', 'head_office': 'Stockholm'},
        {'name': 'Zalando', 'industry': 'E-commerce', 'head_office': 'Berlin'},
        {'name': 'Roche', 'industry': 'Pharmaceuticals', 'head_office': 'Basel'},
        {'name': 'Ikea', 'industry': 'Retail', 'head_office': 'Delft'}
    ]

    # Populate Organizations
    for org in organization_data:
        city = City.objects.filter(city=org['head_office']).first()
        Organization.objects.get_or_create(
            name=org['name'],
            defaults={
                'industry': industries[org['industry']],
                'current_org_head_office': city,
                'current_org_city': city
            }
        )

    # Client data
    client_data = [
        {'name': 'Shekhar Bhosale', 'email': 'shekhar.bhosale@djangopay.com', 'phone': '+917744007724'},
        {'name': 'Priya Patel', 'email': 'priya.patel@djangopay.com', 'phone': '+919876543211'},
        {'name': 'Siddhi Bhosale', 'email': 'siddhi.bhosale@djangopay.com', 'phone': '+918485054307'},
        {'name': 'Neha Joshi', 'email': 'neha.joshi@djangopay.com', 'phone': '+919876543213'},
        {'name': 'Vikram Singh', 'email': 'vikram.singh@djangopay.com', 'phone': '+919876543214'},
        {'name': 'Ananya Nair', 'email': 'ananya.nair@djangopay.com', 'phone': '+919876543215'},
        {'name': 'Arjun Rao', 'email': 'arjun.rao@djangopay.com', 'phone': '+919876543216'},
        {'name': 'Sanya Desai', 'email': 'sanya.desai@djangopay.com', 'phone': '+919876543217'},
        {'name': 'Karan Malhotra', 'email': 'karan.malhotra@djangopay.com', 'phone': '+919876543218'},
        {'name': 'Meera Iyer', 'email': 'meera.iyer@djangopay.com', 'phone': '+919876543219'},
        {'name': 'Takeshi Yamamoto', 'email': 'takeshi.yamamoto@djangopay.com', 'phone': '+81312345678'},
        {'name': 'Ayumi Nakamura', 'email': 'ayumi.nakamura@djangopay.com', 'phone': '+81312345679'},
        {'name': 'Haruka Fujimoto', 'email': 'haruka.fujimoto@djangopay.com', 'phone': '+81312345680'},
        {'name': 'Daichi Sato', 'email': 'daichi.sato@djangopay.com', 'phone': '+81312345681'},
        {'name': 'Yuki Matsumoto', 'email': 'yuki.matsumoto@djangopay.com', 'phone': '+81312345682'},
        {'name': 'Rei Kobayashi', 'email': 'rei.kobayashi@djangopay.com', 'phone': '+81312345683'},
        {'name': 'Sota Nishimura', 'email': 'sota.nishimura@djangopay.com', 'phone': '+81312345684'},
        {'name': 'Mika Takahashi', 'email': 'mika.takahashi@djangopay.com', 'phone': '+81312345685'},
        {'name': 'Kenta Yamada', 'email': 'kenta.yamada@djangopay.com', 'phone': '+81312345686'},
        {'name': 'Naoko Shimizu', 'email': 'naoko.shimizu@djangopay.com', 'phone': '+81312345687'},
        {'name': 'Ji-hoon Kim', 'email': 'jihoon.kim@djangopay.com', 'phone': '+821012345678'},
        {'name': 'Soo-jin Park', 'email': 'soojin.park@djangopay.com', 'phone': '+821012345679'},
        {'name': 'Min-seo Lee', 'email': 'minseo.lee@djangopay.com', 'phone': '+821012345680'},
        {'name': 'Hye-jin Choi', 'email': 'hyejin.choi@djangopay.com', 'phone': '+821012345681 tuned'},
        {'name': 'Jae-hoon Kang', 'email': 'jaehoon.kang@djangopay.com', 'phone': '+821012345682'},
        {'name': 'Eun-ji Shin', 'email': 'eunji.shin@djangopay.com', 'phone': '+821012345683'},
        {'name': 'Tae-hyun Yoon', 'email': 'taehyun.yoon@djangopay.com', 'phone': '+821012345684'},
        {'name': 'Seo-yeon Han', 'email': 'seoyeon.han@djangopay.com', 'phone': '+821012345685'},
        {'name': 'Min-jun Park', 'email': 'minjun.park@djangopay.com', 'phone': '+821012345686'},
        {'name': 'Ji-won Kim', 'email': 'jiwon.kim@djangopay.com', 'phone': '+821012345687'},
        {'name': 'Emma Müller', 'email': 'emma.muller@djangopay.com', 'phone': '+493012345678'},
        {'name': 'Lucas Schmidt', 'email': 'lucas.schmidt@djangopay.com', 'phone': '+493012345679'},
        {'name': 'Sophie Dubois', 'email': 'sophie.dubois@djangopay.com', 'phone': '+33123456789'},
        {'name': 'Matteo Rossi', 'email': 'matteo.rossi@djangopay.com', 'phone': '+390612345678'},
        {'name': 'Isabelle Jansen', 'email': 'isabelle.jansen@djangopay.com', 'phone': '+312012345678'},
        {'name': 'Liam James', 'email': 'liam.oconnor@djangopay.com', 'phone': '+35312345678'},
        {'name': 'Clara Andersen', 'email': 'clara.andersen@djangopay.com', 'phone': '+4523456789'},
        {'name': 'Lukas Weber', 'email': 'lukas.weber@djangopay.com', 'phone': '+41412345678'},
        {'name': 'Elena García', 'email': 'elena.garcia@djangopay.com', 'phone': '+34912345678'},
        {'name': 'Oskar Lindström', 'email': 'oskar.lindstrom@djangopay.com', 'phone': '+46812345678'},
        {'name': 'Amelia Kowalski', 'email': 'amelia.kowalski@djangopay.com', 'phone': '+48223456789'},
        {'name': 'Hugo Lefèvre', 'email': 'hugo.lefevre@djangopay.com', 'phone': '+33123456790'},
        {'name': 'Freya Olsen', 'email': 'freya.olsen@djangopay.com', 'phone': '+47223456789'},
        {'name': 'Viktor Novak', 'email': 'viktor.novak@djangopay.com', 'phone': '+42023456789'},
        {'name': 'Sofia Almeida', 'email': 'sofia.almeida@djangopay.com', 'phone': '+35123456789'},
        {'name': 'Leon Becker', 'email': 'leon.becker@djangopay.com', 'phone': '+493012345680'},
        {'name': 'Mia Sørensen', 'email': 'mia.sorensen@djangopay.com', 'phone': '+4523456790'},
        {'name': 'Noah Fischer', 'email': 'noah.fischer@djangopay.com', 'phone': '+41412345679'},
        {'name': 'Olivia Berg', 'email': 'olivia.berg@djangopay.com', 'phone': '+46812345679'},
        {'name': 'Elias Costa', 'email': 'elias.costa@djangopay.com', 'phone': '+35123456790'}
    ]

    # Populate Clients
    for client in client_data:
        city = City.objects.order_by('?').first()  # Random city
        country = city.country if city else None
        state = city.state if city else None
        region = country.global_region if country else None
        org = Organization.objects.order_by('?').first()  # Random organization
        Client.objects.get_or_create(
            email=client['email'],
            defaults={
                'name': client['name'],
                'phone': client['phone'],
                'current_organization': org,
                'current_org_city': city,
                'current_country': country,
                'current_state': state,
                'current_region': region,
                'industry': org.industry if org else None
            }
        )

class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('clients', '0001_initial'),
        ('locations', '0002_populate_locations'),
    ]
    operations = [
        migrations.RunPython(populate_clients),
    ]
