# Generated by Django 4.2.11 on 2025-06-09 17:50

from django.db import migrations
from django.utils import timezone
import random
import datetime

def generate_random_date(start_days_ago, end_days_ago):
    """Generate a random date between start_days_ago and end_days_ago."""
    now = timezone.now().date()
    days_ago = random.randint(start_days_ago, end_days_ago)
    return now - datetime.timedelta(days=days_ago)

def populate_client_organizations_and_dates(apps, schema_editor):
    Client = apps.get_model('clients', 'Client')
    Organization = apps.get_model('clients', 'Organization')
    ClientOrganization = apps.get_model('clients', 'ClientOrganization')
    
    clients = Client.objects.all()
    organizations = list(Organization.objects.all())
    
    # Assign joining date and populate ClientOrganization
    for client in clients:
        # Fix joining date for current organization
        if client.current_organization and not client.current_org_joining_day:
            client.current_org_joining_day = generate_random_date(10, 365)
            client.save()
        
        # Assign 1-3 past companies to each client
        num_past_companies = random.randint(1, 3)
        available_orgs = [org for org in organizations if org != client.current_organization]
        past_companies = random.sample(available_orgs, min(num_past_companies, len(available_orgs)))
        for org in past_companies:
            to_date = generate_random_date(366, 1000)
            from_date = to_date - datetime.timedelta(days=random.randint(100, 300))
            ClientOrganization.objects.get_or_create(
                client=client,
                organization=org,
                from_date=from_date,
                defaults={
                    'to_date': to_date,
                    'corporate_affiliation_city': org.current_org_head_office
                }
            )

class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('clients', '0002_populate_clients'),
    ]
    operations = [
        migrations.RunPython(populate_client_organizations_and_dates),
    ]
