# Generated by Django 4.2.11 on 2025-10-06 02:29

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import invoices.models.invoice


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('invoices', '0001_initial'),
        ('fincore', '0003_initial'),
        ('entities', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='status',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='status',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(help_text='Invoice this payment is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(help_text='Method used for the payment.', on_delete=django.db.models.deletion.PROTECT, to='invoices.paymentmethod'),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='invoice',
            field=models.ForeignKey(help_text='Invoice this line item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_address',
            field=models.ForeignKey(help_text='Billing address for the invoice.', on_delete=django.db.models.deletion.PROTECT, to='fincore.address'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_country',
            field=models.ForeignKey(help_text='Country associated with the billing address.', on_delete=django.db.models.deletion.PROTECT, to='locations.customcountry'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_region',
            field=models.ForeignKey(blank=True, help_text='Region or state associated with the billing address.', null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.customregion'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issuer',
            field=models.ForeignKey(help_text='Entity issuing the invoice.', on_delete=django.db.models.deletion.PROTECT, related_name='invoices_issued', to='entities.entity'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='recipient',
            field=models.ForeignKey(help_text='Entity receiving the invoice.', on_delete=django.db.models.deletion.PROTECT, related_name='invoices_received', to='entities.entity'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.ForeignKey(default=invoices.models.invoice.Invoice.get_default_status_id, help_text='Status of the invoice.', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='invoices.status'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gstconfiguration',
            name='applicable_region',
            field=models.ForeignKey(blank=True, help_text='Region where this GST configuration applies (optional, for state-specific rates).', null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.customregion'),
        ),
        migrations.AddField(
            model_name='gstconfiguration',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gstconfiguration',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gstconfiguration',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billingschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billingschedule',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billingschedule',
            name='entity',
            field=models.ForeignKey(help_text='Entity associated with this billing schedule.', on_delete=django.db.models.deletion.PROTECT, related_name='billing_schedules', to='entities.entity'),
        ),
        migrations.AddField(
            model_name='billingschedule',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['name', 'code'], name='status_name_3d6648_idx'),
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['is_default'], name='status_is_defa_173056_idx'),
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['is_locked'], name='status_is_lock_a78258_idx'),
        ),
        migrations.AddConstraint(
            model_name='status',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_active_status_name'),
        ),
        migrations.AddConstraint(
            model_name='status',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('code',), name='unique_active_status_code'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['code', 'is_active'], name='payment_met_code_33ab27_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('code',), name='unique_active_payment_method'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice', 'status'], name='payment_inv_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='payment_paymentdate_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=django.contrib.postgres.indexes.GinIndex(fields=['payment_reference'], name='payment_ref_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice'], name='payment_invoice_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method'], name='payment_method_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('payment_reference__isnull', False)), fields=('invoice', 'payment_reference'), name='unique_active_payment_reference'),
        ),
        migrations.AddIndex(
            model_name='lineitem',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='line_item_desc_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='lineitem',
            index=django.contrib.postgres.indexes.GinIndex(fields=['hsn_sac_code'], name='line_item_hsn_sac_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='lineitem',
            index=models.Index(fields=['invoice'], name='line_item_invoice_idx'),
        ),
        migrations.AddIndex(
            model_name='lineitem',
            index=models.Index(fields=['hsn_sac_code'], name='line_item_hsn_sac_idx'),
        ),
        migrations.AddConstraint(
            model_name='lineitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('invoice', 'description', 'hsn_sac_code'), name='unique_active_line_item'),
        ),
        migrations.AddConstraint(
            model_name='lineitem',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='positive_quantity'),
        ),
        migrations.AddConstraint(
            model_name='lineitem',
            constraint=models.CheckConstraint(check=models.Q(('unit_price__gte', 0)), name='non_negative_unit_price'),
        ),
        migrations.AddConstraint(
            model_name='lineitem',
            constraint=models.CheckConstraint(check=models.Q(('discount__gte', 0)), name='non_negative_discount'),
        ),
        migrations.AddConstraint(
            model_name='lineitem',
            constraint=models.CheckConstraint(check=models.Q(('total_amount__gte', 0)), name='non_negative_total_amount'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['issuer', 'recipient'], name='inv_issuer_recpt_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['issue_date', 'due_date'], name='invoice_dates_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['created_by', 'updated_by'], name='invoice_auditby_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=django.contrib.postgres.indexes.GinIndex(fields=['invoice_number'], name='invoice_number_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='invoice_desc_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['issuer'], name='invoice_issuer_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['recipient'], name='invoice_recipient_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['billing_address'], name='invoice_billing_address_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['billing_country'], name='invoice_billing_country_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['billing_region'], name='invoice_billing_region_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='invoice_status_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='invoice_number_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('issuer', 'invoice_number'), name='unique_active_invoice_number'),
        ),
        migrations.AddIndex(
            model_name='gstconfiguration',
            index=models.Index(fields=['applicable_region', 'effective_from', 'rate_type'], name='gst_configu_applica_e0a8a4_idx'),
        ),
        migrations.AddIndex(
            model_name='gstconfiguration',
            index=models.Index(fields=['rate_type'], name='gst_configu_rate_ty_50aa5c_idx'),
        ),
        migrations.AddIndex(
            model_name='gstconfiguration',
            index=models.Index(fields=['effective_from', 'effective_to'], name='gst_configu_effecti_296ba5_idx'),
        ),
        migrations.AddConstraint(
            model_name='gstconfiguration',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('applicable_region', 'effective_from', 'rate_type'), name='unique_active_gst_config'),
        ),
        migrations.AddIndex(
            model_name='billingschedule',
            index=models.Index(fields=['entity', 'frequency'], name='billing_sch_entity__391f67_idx'),
        ),
        migrations.AddIndex(
            model_name='billingschedule',
            index=models.Index(fields=['start_date', 'next_billing_date'], name='billing_sch_start_d_c900f4_idx'),
        ),
        migrations.AddIndex(
            model_name='billingschedule',
            index=models.Index(fields=['status'], name='billing_sch_status_41430b_idx'),
        ),
        migrations.AddConstraint(
            model_name='billingschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('entity', 'description', 'start_date'), name='unique_active_billing_schedule'),
        ),
        migrations.AddConstraint(
            model_name='billingschedule',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='non_negative_amount'),
        ),
    ]
