# Generated by Django 4.2.11 on 2025-06-09 16:57

from django.db import migrations
from django.utils import timezone
import random
import datetime

def generate_random_date(start_days_ago, end_days_ago):
    """Generate a random date between start_days_ago and end_days_ago."""
    now = timezone.now().date()
    days_ago = random.randint(start_days_ago, end_days_ago)
    return now - datetime.timedelta(days=days_ago)

def populate_invoices(apps, schema_editor):
    Client = apps.get_model('clients', 'Client')
    Invoice = apps.get_model('invoices', 'Invoice')
    InvoiceStatus = apps.get_model('invoices', 'InvoiceStatus')
    PaymentMethod = apps.get_model('invoices', 'PaymentMethod')
    InvoicePayment = apps.get_model('invoices', 'InvoicePayment')

    # Define statuses for InvoiceStatus
    statuses = [
        {"name": "Draft", "code": "draft", "is_default": True},
        {"name": "Sent", "code": "sent", "is_default": False},
        {"name": "Paid", "code": "paid", "is_default": False},
        {"name": "Overdue", "code": "overdue", "is_default": False},
        {"name": "Cancelled", "code": "cancelled", "is_default": False},
    ]

    # Define payment methods
    payment_methods = [
        {"name": "Bank Transfer", "code": "bank_transfer"},
        {"name": "Credit Card", "code": "credit_card"},
        {"name": "UPI", "code": "upi"},
        {"name": "Cash", "code": "cash"},
        {"name": "Cheque", "code": "cheque"},
        {"name": "Other", "code": "other"},
    ]

    payment_references = ['TXN-123456', 'REF-789012', 'PAY-345678', 'TRN-901234', None]
    notes = ['Payment due upon receipt', 'Includes additional service charges', 
             'Please contact accounts for queries', 'Discount applied for early payment', None]

    # Create InvoiceStatus and PaymentMethod
    status_objects = {}
    for status in statuses:
        status_obj, _ = InvoiceStatus.objects.get_or_create(
            code=status['code'],
            defaults={
                'name': status['name'],
                'is_default': status['is_default'],
                'is_active': True
            }
        )
        status_objects[status['code']] = status_obj

    payment_method_objects = {}
    for method in payment_methods:
        method_obj, _ = PaymentMethod.objects.get_or_create(
            code=method['code'],
            defaults={
                'name': method['name'],
                'is_active': True
            }
        )
        payment_method_objects[method['code']] = method_obj
    
    def generate_invoice_number_for_migration(issue_date, existing_numbers):
        date_str = issue_date.strftime("%Y%m%d")
        shuffled_date = ''.join(random.sample(date_str, len(date_str)))
        for _ in range(10):
            sequence = f"{random.randint(0, 9999):04d}"
            invoice_number = f"DJP-{shuffled_date}-{sequence}"
            if invoice_number not in existing_numbers:
                existing_numbers.add(invoice_number)
                return invoice_number
        raise ValueError("Failed to generate unique invoice number during migration")

    # Create sample invoices with optional payments
    clients = Client.objects.all()
    for client in clients:
        existing_numbers = set()
        for _ in range(random.randint(2, 4)):
            issue_date = generate_random_date(10, 365)
            due_date = issue_date + datetime.timedelta(days=random.randint(15, 60))
            amount = round(random.uniform(1000.00, 10000.00), 2)
            status = random.choice(list(status_objects.values()))
            note = random.choice(notes)

            invoice_number = generate_invoice_number_for_migration(issue_date, existing_numbers)

            invoice = Invoice.objects.create(
                client=client,
                issue_date=issue_date,
                due_date=due_date,
                amount=amount,
                status=status,
                notes=note,
                invoice_number=invoice_number,
                created_at=issue_date,
                updated_at=issue_date
            )

            # Add 0–2 payments randomly for some invoices
            if status.code in ['paid', 'overdue', 'sent']:
                for _ in range(random.randint(0, 2)):
                    payment_amount = round(random.uniform(100, amount), 2)
                    naive_paid_at = datetime.datetime.combine(
                        issue_date, datetime.time(0, 0)
                    ) + datetime.timedelta(days=random.randint(0, 30))
                    aware_paid_at = timezone.make_aware(naive_paid_at, timezone.get_default_timezone())
                    InvoicePayment.objects.create(
                        invoice=invoice,
                        amount=payment_amount,
                        method=random.choice(list(payment_method_objects.values())),
                        reference=random.choice(payment_references),
                        paid_at=aware_paid_at
                    )

class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('invoices', '0001_initial'),
        ('clients', '0002_populate_clients'),
    ]
    operations = [
        migrations.RunPython(populate_invoices),
    ]