# Generated by Django 4.2.11 on 2025-06-09 17:51

from django.db import migrations
from django.utils import timezone
import random
import datetime

def fix_invoice_payment_times(apps, schema_editor):
    InvoicePayment = apps.get_model('invoices', 'InvoicePayment')
    
    for payment in InvoicePayment.objects.all():
        if payment.paid_at:
            # Get the original date
            original_date = payment.paid_at.date()
            # Generate a random time (e.g., between 8:00 AM and 6:00 PM)
            random_hour = random.randint(8, 18)
            random_minute = random.randint(0, 59)
            random_second = random.randint(0, 59)
            # Combine date with random time
            naive_paid_at = datetime.datetime.combine(
                original_date,
                datetime.time(random_hour, random_minute, random_second)
            )
            # Make it timezone-aware
            aware_paid_at = timezone.make_aware(naive_paid_at, timezone.get_default_timezone())
            payment.paid_at = aware_paid_at
            payment.save()

class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('invoices', '0002_populate_invoices'),
    ]
    operations = [
        migrations.RunPython(fix_invoice_payment_times),
    ]