# Generated by Django 4.2.11 on 2025-10-06 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(blank=True, choices=[], default='INR', help_text='Currency of the invoice.', max_length=3),
        ),
    ]
