# Generated by Django 4.2.11 on 2025-10-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_invoice_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(blank=True, choices=[('THB', 'THB'), ('CDF', 'CDF'), ('HKD', 'HKD'), ('IDR', 'IDR'), ('TRY', 'TRY'), ('ETB', 'ETB'), ('ILS', 'ILS'), ('MOP', 'MOP'), ('SYP', 'SYP'), ('AOA', 'AOA'), ('SCR', 'SCR'), ('MRU', 'MRU'), ('GTQ', 'GTQ'), ('HUF', 'HUF'), ('MXN', 'MXN'), ('CVE', 'CVE'), ('RUB', 'RUB'), ('JMD', 'JMD'), ('AWG', 'AWG'), ('ZAR', 'ZAR'), ('SAR', 'SAR'), ('BWP', 'BWP'), ('TOP', 'TOP'), ('MNT', 'MNT'), ('IRR', 'IRR'), ('UYU', 'UYU'), ('MYR', 'MYR'), ('TTD', 'TTD'), ('ANG', 'ANG'), ('BND', 'BND'), ('BTN', 'BTN'), ('QAR', 'QAR'), ('SHP', 'SHP'), ('CUP', 'CUP'), ('BMD', 'BMD'), ('SDG', 'SDG'), ('LAK', 'LAK'), ('AED', 'AED'), ('CLP', 'CLP'), ('RSD', 'RSD'), ('KGS', 'KGS'), ('KES', 'KES'), ('XPF', 'XPF'), ('AZN', 'AZN'), ('XCD', 'XCD'), ('AFN', 'AFN'), ('KPW', 'KPW'), ('ERN', 'ERN'), ('AUD', 'AUD'), ('NGN', 'NGN'), ('BGN', 'BGN'), ('TWD', 'TWD'), ('LYD', 'LYD'), ('NPR', 'NPR'), ('PLN', 'PLN'), ('COP', 'COP'), ('CRC', 'CRC'), ('BHD', 'BHD'), ('PKR', 'PKR'), ('XOF', 'XOF'), ('GBP', 'GBP'), ('ZWG', 'ZWG'), ('TND', 'TND'), ('OMR', 'OMR'), ('MZN', 'MZN'), ('GYD', 'GYD'), ('CZK', 'CZK'), ('MGA', 'MGA'), ('DKK', 'DKK'), ('KYD', 'KYD'), ('GIP', 'GIP'), ('MVR', 'MVR'), ('SSP', 'SSP'), ('RON', 'RON'), ('STN', 'STN'), ('RWF', 'RWF'), ('NAD', 'NAD'), ('JOD', 'JOD'), ('VUV', 'VUV'), ('BBD', 'BBD'), ('UAH', 'UAH'), ('CHF', 'CHF'), ('SOS', 'SOS'), ('CAD', 'CAD'), ('GEL', 'GEL'), ('LKR', 'LKR'), ('BOB', 'BOB'), ('MDL', 'MDL'), ('NZD', 'NZD'), ('MMK', 'MMK'), ('LRD', 'LRD'), ('VND', 'VND'), ('PGK', 'PGK'), ('VES', 'VES'), ('PYG', 'PYG'), ('BZD', 'BZD'), ('SRD', 'SRD'), ('SEK', 'SEK'), ('DZD', 'DZD'), ('ARS', 'ARS'), ('KHR', 'KHR'), ('FJD', 'FJD'), ('PEN', 'PEN'), ('UZS', 'UZS'), ('DJF', 'DJF'), ('BRL', 'BRL'), ('HNL', 'HNL'), ('LBP', 'LBP'), ('EGP', 'EGP'), ('TJS', 'TJS'), ('USD', 'USD'), ('FKP', 'FKP'), ('TMT', 'TMT'), ('PHP', 'PHP'), ('LSL', 'LSL'), ('ISK', 'ISK'), ('YER', 'YER'), ('SBD', 'SBD'), ('SLE', 'SLE'), ('MUR', 'MUR'), ('CNY', 'CNY'), ('PAB', 'PAB'), ('BAM', 'BAM'), ('NOK', 'NOK'), ('KMF', 'KMF'), ('BDT', 'BDT'), ('INR', 'INR'), ('HTG', 'HTG'), ('ALL', 'ALL'), ('MWK', 'MWK'), ('MAD', 'MAD'), ('GMD', 'GMD'), ('AMD', 'AMD'), ('KRW', 'KRW'), ('UGX', 'UGX'), ('DOP', 'DOP'), ('MKD', 'MKD'), ('KWD', 'KWD'), ('EUR', 'EUR'), ('TZS', 'TZS'), ('BYN', 'BYN'), ('ZMW', 'ZMW'), ('XAF', 'XAF'), ('NIO', 'NIO'), ('KZT', 'KZT'), ('SGD', 'SGD'), ('JPY', 'JPY'), ('IQD', 'IQD'), ('WST', 'WST'), ('BIF', 'BIF'), ('GHS', 'GHS'), ('SZL', 'SZL'), ('BSD', 'BSD'), ('GNF', 'GNF')], default='INR', help_text='Currency of the invoice.', max_length=3),
        ),
    ]
