# Generated by Django 5.2.8 on 2025-11-20 11:32

import invoices.services.invoice
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_invoice_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(blank=True, choices=invoices.services.invoice.get_currency_choices, default='INR', help_text='Currency of the invoice.', max_length=3),
        ),
    ]
