# Generated by Django 5.2.8 on 2025-11-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_alter_invoice_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(blank=True, choices=[('INR', 'INR')], default='INR', help_text='Currency of the invoice.', max_length=3),
        ),
    ]
