# Generated by Django 4.2.11 on 2026-01-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_historicalbillingschedule_historicalgstconfiguration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoice',
            name='currency',
            field=models.CharField(blank=True, default='INR', help_text='Currency of the invoice.', max_length=3),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(blank=True, default='INR', help_text='Currency of the invoice.', max_length=3),
        ),
    ]
