from django.db import models
from django.utils import timezone


class AuditEvent(models.Model):

    """
    Immutable audit log entry.

    This model is intentionally:
    - Append-only
    - Denormalized
    - Free of foreign keys to domain models

    It represents a factual record of something that already happened.
    """

    # ------------------------------------------------------------------
    # Core identity
    # ------------------------------------------------------------------
    id = models.BigAutoField(primary_key=True)

    occurred_at = models.DateTimeField(
        default=timezone.now,
        db_index=True,
        help_text="When the audited action occurred."
    )

    # ------------------------------------------------------------------
    # Action
    # ------------------------------------------------------------------
    action = models.CharField(
        max_length=64,
        db_index=True,
        help_text="Canonical action name (e.g. create, update, delete, login)."
    )

    # ------------------------------------------------------------------
    # Actor (who)
    # ------------------------------------------------------------------
    actor_id = models.CharField(
        max_length=64,
        null=True,
        blank=True,
        db_index=True,
        help_text="Identifier of the actor (user id, service id, etc.)."
    )

    actor_type = models.CharField(
        max_length=32,
        null=True,
        blank=True,
        help_text="Type of actor (user, system, service)."
    )

    actor_label = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        help_text="Human-readable actor identifier (email, username)."
    )

    # ------------------------------------------------------------------
    # Target (what)
    # ------------------------------------------------------------------
    target_type = models.CharField(
        max_length=64,
        null=True,
        blank=True,
        db_index=True,
        help_text="Type of entity affected (invoice, client, member, etc.)."
    )

    target_id = models.CharField(
        max_length=64,
        null=True,
        blank=True,
        db_index=True,
        help_text="Identifier of the affected entity."
    )

    target_label = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        help_text="Human-readable target identifier."
    )

    # ------------------------------------------------------------------
    # Request / execution context
    # ------------------------------------------------------------------
    request_id = models.CharField(
        max_length=64,
        null=True,
        blank=True,
        db_index=True,
        help_text="Request ID for correlating distributed actions."
    )

    client_ip = models.GenericIPAddressField(
        null=True,
        blank=True,
        help_text="Client IP address, if available."
    )

    user_agent = models.TextField(
        null=True,
        blank=True,
        help_text="User agent string, if available."
    )

    # ------------------------------------------------------------------
    # Extra data
    # ------------------------------------------------------------------
    metadata = models.JSONField(
        default=dict,
        blank=True,
        help_text="Arbitrary structured metadata relevant to the event."
    )

    # ------------------------------------------------------------------
    # System flags
    # ------------------------------------------------------------------
    is_system_event = models.BooleanField(
        default=False,
        help_text="True if generated by system/middleware rather than a user."
    )

    class Meta:
        db_table = "audit_event"
        ordering = ["-occurred_at"]
        indexes = [
            models.Index(fields=["action", "occurred_at"]),
            models.Index(fields=["target_type", "target_id"]),
        ]

        managed = True

    def __str__(self) -> str:
        return f"[{self.occurred_at}] {self.action} ({self.target_type}:{self.target_id})"
