# Generated by Django 4.2.11 on 2025-10-06 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Name of the entity (e.g., company name, individual name).', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier for the entity.', max_length=255, unique=True)),
                ('entity_type', models.CharField(blank=True, choices=[('INDIVIDUAL', 'Individual'), ('BUSINESS', 'Business'), ('GOVERNMENT', 'Government'), ('NONPROFIT', 'Nonprofit'), ('PARTNERSHIP', 'Partnership'), ('SOLE_PROPRIETORSHIP', 'Sole Proprietorship'), ('OTHER', 'Other')], default='BUSINESS', help_text='Type of entity...', max_length=20)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('ON_HOLD', 'On Hold')], default='ACTIVE', help_text='Status of the entity...', max_length=20)),
                ('external_id', models.CharField(blank=True, help_text='External identifier for integration with other systems.', max_length=100, null=True, unique=True)),
                ('website', models.URLField(blank=True, help_text="Entity's website URL.")),
                ('registration_number', models.CharField(blank=True, help_text='Registration number (e.g., CIN, GSTIN, EIN).', max_length=50)),
                ('entity_size', models.CharField(blank=True, help_text='Size of the entity (e.g., Small, Medium, Large).', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the entity.')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'Entity',
                'verbose_name_plural': 'Companies',
                'db_table': 'entity',
                'ordering': ['name'],
            },
        ),
    ]
