# Generated by Django 4.2.11 on 2025-10-06 02:29

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        ('fincore', '0002_initial'),
        ('industries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entity',
            name='default_address',
            field=models.ForeignKey(blank=True, help_text='Default address for the entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_entities', to='fincore.address'),
        ),
        migrations.AddField(
            model_name='entity',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entity',
            name='industry',
            field=models.ForeignKey(blank=True, help_text='Industry classification for the entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='industries.industry'),
        ),
        migrations.AddField(
            model_name='entity',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Parent entity in the organizational hierarchy.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='entities.entity'),
        ),
        migrations.AddField(
            model_name='entity',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['name', 'entity_type', 'status'], name='entity_name_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['name', 'slug'], name='entity_name_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['external_id'], name='entity_ext_id_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['created_by'], name='entity_created_by_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['updated_by'], name='entity_updated_by_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['deleted_by'], name='entity_deleted_by_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='entity_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=django.contrib.postgres.indexes.GinIndex(fields=['registration_number'], name='entity_reg_number_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['industry'], name='entity_industry_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['status'], name='entity_status_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['default_address'], name='entity_default_address_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['slug'], name='entity_slug_idx'),
        ),
        migrations.AddConstraint(
            model_name='entity',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name', 'entity_type'), name='unique_active_entity_name_type'),
        ),
        migrations.AddConstraint(
            model_name='entity',
            constraint=models.CheckConstraint(check=models.Q(('entity_type__in', ['INDIVIDUAL', 'BUSINESS', 'GOVERNMENT', 'NONPROFIT', 'PARTNERSHIP', 'SOLE_PROPRIETORSHIP', 'OTHER'])), name='valid_entity_type'),
        ),
        migrations.AddConstraint(
            model_name='entity',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['PENDING', 'ACTIVE', 'INACTIVE', 'SUSPENDED', 'ON_HOLD'])), name='valid_entity_status'),
        ),
    ]
