# Generated by Django 5.2.8 on 2025-11-24 12:45

import django.db.models.deletion
import mptt.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_initial'),
        ('fincore', '0003_initial'),
        ('industries', '0003_historicalindustry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEntity',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Name of the entity (e.g., company name, individual name).', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier for the entity.', max_length=255)),
                ('entity_type', models.CharField(blank=True, choices=[('INDIVIDUAL', 'Individual'), ('BUSINESS', 'Business'), ('GOVERNMENT', 'Government'), ('NONPROFIT', 'Nonprofit'), ('PARTNERSHIP', 'Partnership'), ('SOLE_PROPRIETORSHIP', 'Sole Proprietorship'), ('OTHER', 'Other')], default='BUSINESS', help_text='Type of entity...', max_length=20)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('ON_HOLD', 'On Hold')], default='ACTIVE', help_text='Status of the entity...', max_length=20)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External identifier for integration with other systems.', max_length=100, null=True)),
                ('website', models.URLField(blank=True, help_text="Entity's website URL.")),
                ('registration_number', models.CharField(blank=True, help_text='Registration number (e.g., CIN, GSTIN, EIN).', max_length=50)),
                ('entity_size', models.CharField(blank=True, help_text='Size of the entity (e.g., Small, Medium, Large).', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the entity.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this object.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('default_address', models.ForeignKey(blank=True, db_constraint=False, help_text='Default address for the entity.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fincore.address')),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who deleted this object.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('industry', models.ForeignKey(blank=True, db_constraint=False, help_text='Industry classification for the entity.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='industries.industry')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, db_constraint=False, help_text='Parent entity in the organizational hierarchy.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entities.entity')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Entity',
                'verbose_name_plural': 'historical Companies',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
