# Generated by Django 5.2.8 on 2025-12-12 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_historicalentity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['name'], 'verbose_name': 'Business', 'verbose_name_plural': 'Businesses'},
        ),
        migrations.AlterModelOptions(
            name='historicalentity',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Business', 'verbose_name_plural': 'historical Businesses'},
        ),
    ]
