# Generated by Django 4.2.11 on 2026-01-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='emails_sent',
            field=models.BooleanField(default=False, help_text='True if email has been sent'),
        ),
        migrations.AddField(
            model_name='historicalbugreport',
            name='emails_sent',
            field=models.BooleanField(default=False, help_text='True if email has been sent'),
        ),
        migrations.AddField(
            model_name='historicalsupportticket',
            name='emails_sent',
            field=models.BooleanField(default=False, help_text='True if email has been sent'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='emails_sent',
            field=models.BooleanField(default=False, help_text='True if email has been sent'),
        ),
    ]
