# Generated by Django 4.2.11 on 2026-03-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_bugreport_emails_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='migrated_issue_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbugreport',
            name='migrated_issue_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsupportticket',
            name='migrated_issue_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='migrated_issue_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
