# Generated by Django 4.2.11 on 2025-10-06 02:29

from django.db import migrations, models
import utilities.utils.locations.phone_number_validations
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('address_type', models.CharField(choices=[('BILLING', 'Billing'), ('SHIPPING', 'Shipping'), ('REGISTERED', 'Registered'), ('OPERATIONAL', 'Operational'), ('HEADQUARTERS', 'Headquarters'), ('OFFICE', 'Office')], default='BILLING', help_text='Type of address (e.g., Billing, Shipping).', max_length=20)),
                ('street_address', models.CharField(blank=True, help_text='Street address, mapped to Location.street_address.', max_length=255)),
                ('postal_code', models.CharField(blank=True, help_text='Postal code for the address, validated per country.', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default address for the entity.')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'db_table': 'address',
                'ordering': ['city__name', 'address_type'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Full name of the contact.', max_length=255)),
                ('email', models.EmailField(blank=True, help_text='Email address of the contact.', max_length=254)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number in international format (e.g., +1234567890).', max_length=20, validators=[utilities.utils.locations.phone_number_validations.validate_phone_number])),
                ('role', models.CharField(choices=[('BILLING', 'Billing'), ('TECHNICAL', 'Technical'), ('LEGAL', 'Legal'), ('PRIMARY', 'Primary')], default='PRIMARY', help_text='Role of the contact (e.g., Billing, Technical).', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary contact for the entity.')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'contact',
                'ordering': ['name', 'role'],
            },
        ),
        migrations.CreateModel(
            name='FincoreEntityMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('entity_uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID for the entity mapping.', unique=True)),
                ('entity_type', models.CharField(help_text="Type of entity (e.g., 'entities.Entity', 'vendors.Vendor').", max_length=50)),
                ('entity_id', models.CharField(help_text='ID of the entity in its app.', max_length=100)),
                ('content_type', models.CharField(help_text="App and model name (e.g., 'entities.Entity').", max_length=100)),
            ],
            options={
                'verbose_name': 'Fincore Entity Mapping',
                'verbose_name_plural': 'Fincore Entity Mappings',
                'db_table': 'fincore_entity_mapping',
            },
        ),
        migrations.CreateModel(
            name='TaxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tax_identifier', models.CharField(blank=True, help_text='Tax identifier (e.g., GSTIN, VAT, EIN).', max_length=50)),
                ('tax_identifier_type', models.CharField(choices=[('GSTIN', 'GSTIN (India)'), ('VAT', 'VAT (EU)'), ('EIN', 'EIN (USA)'), ('PAN', 'PAN (India)'), ('OTHER', 'Other')], default='GSTIN', help_text='Type of tax identifier.', max_length=20)),
                ('is_tax_exempt', models.BooleanField(default=False, help_text='Whether the entity is tax-exempt.')),
                ('tax_exemption_reason', models.TextField(blank=True, help_text='Reason for tax exemption, if applicable.')),
                ('tax_exemption_document', models.FileField(blank=True, help_text='Document supporting tax exemption, if applicable.', null=True, upload_to='tax_exemptions/')),
            ],
            options={
                'verbose_name': 'Tax Profile',
                'verbose_name_plural': 'Tax Profiles',
                'db_table': 'tax_profile',
                'ordering': ['tax_identifier_type', 'country__country_code'],
            },
        ),
    ]
