# Generated by Django 4.2.11 on 2025-10-06 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('fincore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxprofile',
            name='country',
            field=models.ForeignKey(help_text='Country associated with the tax profile.', on_delete=django.db.models.deletion.PROTECT, related_name='tax_profiles', to='locations.customcountry'),
        ),
    ]
