# Generated by Django 4.2.11 on 2025-10-06 02:29

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('fincore', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taxprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxprofile',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxprofile',
            name='entity_mapping',
            field=models.ForeignKey(blank=True, help_text='Entity mapping associated with this tax profile.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fincore_entity_tax_profiles', to='fincore.fincoreentitymapping'),
        ),
        migrations.AddField(
            model_name='taxprofile',
            name='region',
            field=models.ForeignKey(blank=True, help_text='Region or state associated with the tax profile.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_profiles', to='locations.customregion'),
        ),
        migrations.AddField(
            model_name='taxprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='fincoreentitymapping',
            index=models.Index(fields=['entity_uuid'], name='fincore_ent_entity__02fdde_idx'),
        ),
        migrations.AddIndex(
            model_name='fincoreentitymapping',
            index=models.Index(fields=['entity_type', 'entity_id'], name='fincore_ent_entity__cb9de0_idx'),
        ),
        migrations.AddIndex(
            model_name='fincoreentitymapping',
            index=models.Index(fields=['entity_type', 'entity_id', 'entity_uuid'], name='entity_mapping_lookup_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fincoreentitymapping',
            unique_together={('entity_type', 'entity_id')},
        ),
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Country associated with the contact for phone number validation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='locations.customcountry'),
        ),
        migrations.AddField(
            model_name='contact',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='entity_mapping',
            field=models.ForeignKey(blank=True, help_text='Entity mapping associated with this contact.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fincore_entity_contacts', to='fincore.fincoreentitymapping'),
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(help_text='City where the address is located.', on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='locations.customcity'),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(help_text='Country where the address is located.', on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='locations.customcountry'),
        ),
        migrations.AddField(
            model_name='address',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='address',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='address',
            name='entity_mapping',
            field=models.ForeignKey(blank=True, help_text='Entity mapping associated with this address.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fincore_entity_addresses', to='fincore.fincoreentitymapping'),
        ),
        migrations.AddField(
            model_name='address',
            name='region',
            field=models.ForeignKey(blank=True, help_text='Region or state where the address is located.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='locations.customregion'),
        ),
        migrations.AddField(
            model_name='address',
            name='subregion',
            field=models.ForeignKey(blank=True, help_text='Subregion or district where the address is located.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='locations.customsubregion'),
        ),
        migrations.AddField(
            model_name='address',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='taxprofile',
            index=models.Index(fields=['entity_mapping', 'tax_identifier_type', 'is_tax_exempt'], name='tax_ent_type_exm_idx'),
        ),
        migrations.AddIndex(
            model_name='taxprofile',
            index=models.Index(fields=['tax_identifier'], name='tax_profile_tax_ide_f5ea95_idx'),
        ),
        migrations.AddIndex(
            model_name='taxprofile',
            index=models.Index(fields=['country'], name='tax_profile_country_17c2be_idx'),
        ),
        migrations.AddIndex(
            model_name='taxprofile',
            index=models.Index(fields=['region'], name='tax_profile_region__9a6794_idx'),
        ),
        migrations.AddIndex(
            model_name='taxprofile',
            index=models.Index(fields=['is_tax_exempt'], name='tax_profile_is_tax__ce7bb6_idx'),
        ),
        migrations.AddIndex(
            model_name='taxprofile',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tax_identifier'], name='tax_id_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='taxprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('entity_mapping', 'tax_identifier', 'tax_identifier_type'), name='unique_active_tax_profile'),
        ),
        migrations.AddConstraint(
            model_name='taxprofile',
            constraint=models.CheckConstraint(check=models.Q(('tax_identifier_type__in', ['GSTIN', 'VAT', 'EIN', 'PAN', 'OTHER'])), name='valid_tax_identifier_type'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['entity_mapping', 'role', 'is_primary'], name='cont_ent_role_prim_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email'], name='contact_email_7a7031_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['country'], name='contact_country_4bf389_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['is_primary'], name='contact_is_prim_0f3add_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='contact_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=django.contrib.postgres.indexes.GinIndex(fields=['email'], name='contact_email_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('entity_mapping', 'email', 'role'), name='unique_active_contact'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.CheckConstraint(check=models.Q(('role__in', ['BILLING', 'TECHNICAL', 'LEGAL', 'PRIMARY'])), name='valid_contact_role'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['entity_mapping', 'address_type', 'is_default'], name='addr_ent_type_def_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['city', 'country'], name='address_city_id_3501dd_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['is_default'], name='address_is_defa_80f2d6_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=django.contrib.postgres.indexes.GinIndex(fields=['street_address'], name='address_street_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='address',
            index=django.contrib.postgres.indexes.GinIndex(fields=['postal_code'], name='address_postal_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('entity_mapping', 'address_type', 'street_address', 'city'), name='unique_active_address'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.CheckConstraint(check=models.Q(('address_type__in', ['BILLING', 'SHIPPING', 'REGISTERED', 'OPERATIONAL', 'HEADQUARTERS', 'OFFICE'])), name='valid_address_type'),
        ),
    ]
