# Generated by Django 5.2.8 on 2025-11-24 12:45

import django.db.models.deletion
import simple_history.models
import utilities.utils.locations.phone_number_validations
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fincore', '0003_initial'),
        ('locations', '0003_alter_customcountry_name_alter_customregion_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAddress',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('address_type', models.CharField(choices=[('BILLING', 'Billing'), ('SHIPPING', 'Shipping'), ('REGISTERED', 'Registered'), ('OPERATIONAL', 'Operational'), ('HEADQUARTERS', 'Headquarters'), ('OFFICE', 'Office')], default='BILLING', help_text='Type of address (e.g., Billing, Shipping).', max_length=20)),
                ('street_address', models.CharField(blank=True, help_text='Street address, mapped to Location.street_address.', max_length=255)),
                ('postal_code', models.CharField(blank=True, help_text='Postal code for the address, validated per country.', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default address for the entity.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('city', models.ForeignKey(blank=True, db_constraint=False, help_text='City where the address is located.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='locations.customcity')),
                ('country', models.ForeignKey(blank=True, db_constraint=False, help_text='Country where the address is located.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='locations.customcountry')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this object.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who deleted this object.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entity_mapping', models.ForeignKey(blank=True, db_constraint=False, help_text='Entity mapping associated with this address.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fincore.fincoreentitymapping')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, db_constraint=False, help_text='Region or state where the address is located.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='locations.customregion')),
                ('subregion', models.ForeignKey(blank=True, db_constraint=False, help_text='Subregion or district where the address is located.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='locations.customsubregion')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Address',
                'verbose_name_plural': 'historical Addresses',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalContact',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Full name of the contact.', max_length=255)),
                ('email', models.EmailField(blank=True, help_text='Email address of the contact.', max_length=254)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number in international format (e.g., +1234567890).', max_length=20, validators=[utilities.utils.locations.phone_number_validations.validate_phone_number])),
                ('role', models.CharField(choices=[('BILLING', 'Billing'), ('TECHNICAL', 'Technical'), ('LEGAL', 'Legal'), ('PRIMARY', 'Primary')], default='PRIMARY', help_text='Role of the contact (e.g., Billing, Technical).', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary contact for the entity.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('country', models.ForeignKey(blank=True, db_constraint=False, help_text='Country associated with the contact for phone number validation.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='locations.customcountry')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this object.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who deleted this object.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entity_mapping', models.ForeignKey(blank=True, db_constraint=False, help_text='Entity mapping associated with this contact.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fincore.fincoreentitymapping')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Contact',
                'verbose_name_plural': 'historical Contacts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFincoreEntityMapping',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('entity_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for the entity mapping.')),
                ('entity_type', models.CharField(help_text="Type of entity (e.g., 'entities.Entity', 'vendors.Vendor').", max_length=50)),
                ('entity_id', models.CharField(help_text='ID of the entity in its app.', max_length=100)),
                ('content_type', models.CharField(help_text="App and model name (e.g., 'entities.Entity').", max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Fincore Entity Mapping',
                'verbose_name_plural': 'historical Fincore Entity Mappings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTaxProfile',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tax_identifier', models.CharField(blank=True, help_text='Tax identifier (e.g., GSTIN, VAT, EIN).', max_length=50)),
                ('tax_identifier_type', models.CharField(choices=[('GSTIN', 'GSTIN (India)'), ('VAT', 'VAT (EU)'), ('EIN', 'EIN (USA)'), ('PAN', 'PAN (India)'), ('OTHER', 'Other')], default='GSTIN', help_text='Type of tax identifier.', max_length=20)),
                ('is_tax_exempt', models.BooleanField(default=False, help_text='Whether the entity is tax-exempt.')),
                ('tax_exemption_reason', models.TextField(blank=True, help_text='Reason for tax exemption, if applicable.')),
                ('tax_exemption_document', models.TextField(blank=True, help_text='Document supporting tax exemption, if applicable.', max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('country', models.ForeignKey(blank=True, db_constraint=False, help_text='Country associated with the tax profile.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='locations.customcountry')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this object.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who deleted this object.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entity_mapping', models.ForeignKey(blank=True, db_constraint=False, help_text='Entity mapping associated with this tax profile.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fincore.fincoreentitymapping')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, db_constraint=False, help_text='Region or state associated with the tax profile.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='locations.customregion')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Tax Profile',
                'verbose_name_plural': 'historical Tax Profiles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
