# Generated by Django 4.2.11 on 2025-06-18 12:06

from decimal import Decimal
from django.conf import settings
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_code', models.CharField(editable=False, help_text='Unique Employee Code in the format DJP1234567890', max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^DJP\\d{10}$', message='Employee Code must be in the format DJP1234567890')])),
                ('department', models.CharField(choices=[('AP', 'Accounts Payable'), ('AR', 'Accounts Receivable'), ('AUD', 'Audit'), ('FIN', 'Finance'), ('MGT', 'Management'), ('OT', 'Other')], default='OT', max_length=3)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\+?[1-9]\\d{7,14}$', message='Phone number must be valid.')])),
                ('job_title', models.CharField(blank=True, max_length=128)),
                ('region', models.CharField(blank=True, help_text='Geographic region or location', max_length=100)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('ACCOUNTANT', 'Accountant'), ('MANAGER', 'Manager'), ('AUDITOR', 'Auditor'), ('CLERK', 'Clerk'), ('CEO', 'CEO')], default='CLERK', max_length=20)),
                ('approval_limit', models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum amount user can approve', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('avatar', models.ImageField(blank=True, help_text='Upload a profile photo', null=True, upload_to='avatars/')),
                ('timezone', models.CharField(default='IST', help_text='User time zone for multi-region teams', max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_user', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('manager', models.ForeignKey(blank=True, help_text='Manager of this employee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by_user', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['id'], name='users_user_id_1cecd0_idx'), models.Index(fields=['employee_code'], name='users_user_employe_bbbdcb_idx'), models.Index(fields=['email', 'username'], name='users_user_email_e67c6c_idx'), models.Index(fields=['department', 'role'], name='users_user_departm_af473a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('employee_code',), name='unique_employee_code'),
        ),
    ]
