# Generated by Django 4.2.11 on 2025-10-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default='2023-01-01', help_text='Hire date'),
            preserve_default=False,
        ),
    ]
