# Generated by Django 4.2.11 on 2025-10-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_employee_hire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='is_bug_report',
            field=models.BooleanField(default=False, help_text='True if this is a bug report'),
        ),
    ]
