# Generated by Django 4.2.11 on 2025-10-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_supportticket_is_bug_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_unsubscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='unsubscribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
