# Generated by Django 4.2.11 on 2025-11-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_employee_is_unsubscribed_employee_unsubscribed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='emails_sent',
            field=models.BooleanField(default=False, help_text='True if email have been sent'),
        ),
    ]
