# Generated by Django 4.2.11 on 2025-11-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_supportticket_emails_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
