# Generated by Django 4.2.11 on 2025-11-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_supportticket_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='github_issue',
            field=models.URLField(blank=True, null=True),
        ),
    ]
