# Generated by Django 4.2.11 on 2025-11-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_employee_address_alter_employee_approval_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(help_text="Unique department code (e.g., 'FIN')", max_length=12, unique=True),
        ),
    ]
