# Generated by Django 5.2.8 on 2025-12-13 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_useractivitylog_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='users.employee'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='manager',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.employee'),
        ),
        migrations.AlterField(
            model_name='historicalleaveapplication',
            name='approver',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Approver', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.employee'),
        ),
        migrations.AlterField(
            model_name='historicalleaveapplication',
            name='employee',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Employee', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.employee'),
        ),
        migrations.AlterField(
            model_name='historicalleavebalance',
            name='employee',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Employee', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.employee'),
        ),
        migrations.AlterField(
            model_name='historicalmember',
            name='employee',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Associated Employee for authentication', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.employee'),
        ),
        migrations.AlterField(
            model_name='historicalsupportticket',
            name='employee',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Associated employee (if authenticated user)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.employee'),
        ),
        migrations.AlterField(
            model_name='historicalteam',
            name='leader',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Team leader', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.employee'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='approver',
            field=models.ForeignKey(blank=True, help_text='Approver', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to='users.employee'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='employee',
            field=models.ForeignKey(help_text='Employee', on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='users.employee'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='employee',
            field=models.ForeignKey(help_text='Employee', on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='users.employee'),
        ),
        migrations.AlterField(
            model_name='member',
            name='employee',
            field=models.OneToOneField(help_text='Associated Employee for authentication', on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to='users.employee'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='Associated employee (if authenticated user)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='users.employee'),
        ),
        migrations.AlterField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(blank=True, help_text='Team leader', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to='users.employee'),
        ),
    ]
