# Generated by Django 5.2.8 on 2025-12-17 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_employee_manager_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalsignuprequest',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical sign up request', 'verbose_name_plural': 'historical sign up requests'},
        ),
        migrations.AlterModelOptions(
            name='signuprequest',
            options={},
        ),
        migrations.AlterField(
            model_name='historicalsignuprequest',
            name='expires_at',
            field=models.DateTimeField(help_text='Expiration timestamp'),
        ),
        migrations.AlterField(
            model_name='historicalsignuprequest',
            name='sso_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsignuprequest',
            name='sso_provider',
            field=models.CharField(choices=[('GOOGLE', 'Google'), ('APPLE', 'Apple'), ('EMAIL', 'Email')], default='EMAIL', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalsignuprequest',
            name='token',
            field=models.CharField(db_index=True, help_text='Opaque email verification token', max_length=64),
        ),
        migrations.AlterField(
            model_name='historicalsignuprequest',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='signuprequest',
            name='expires_at',
            field=models.DateTimeField(help_text='Expiration timestamp'),
        ),
        migrations.AlterField(
            model_name='signuprequest',
            name='sso_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='signuprequest',
            name='sso_provider',
            field=models.CharField(choices=[('GOOGLE', 'Google'), ('APPLE', 'Apple'), ('EMAIL', 'Email')], default='EMAIL', max_length=20),
        ),
        migrations.AlterField(
            model_name='signuprequest',
            name='token',
            field=models.CharField(db_index=True, help_text='Opaque email verification token', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='signuprequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signup_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
