# Generated by Django 5.2.8 on 2025-12-20 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_historicalsignuprequest_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsupportticket',
            old_name='ip_address',
            new_name='client_ip',
        ),
        migrations.RenameField(
            model_name='historicaluseractivitylog',
            old_name='ip_address',
            new_name='client_ip',
        ),
        migrations.RenameField(
            model_name='supportticket',
            old_name='ip_address',
            new_name='client_ip',
        ),
        migrations.RenameField(
            model_name='useractivitylog',
            old_name='ip_address',
            new_name='client_ip',
        ),
    ]
