# Generated by Django 5.2.8 on 2025-12-24 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_ip_address_historicalsupportticket_client_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpasswordresetrequest',
            name='token',
            field=models.CharField(db_index=True, help_text='Opaque password reset token (pwd_*)', max_length=80),
        ),
        migrations.AlterField(
            model_name='historicalpasswordresetrequest',
            name='used',
            field=models.BooleanField(default=False, help_text='Whether this token was consumed successfully'),
        ),
        migrations.AlterField(
            model_name='historicalpasswordresetrequest',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User requesting password reset', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(db_index=True, help_text='Opaque password reset token (pwd_*)', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='used',
            field=models.BooleanField(default=False, help_text='Whether this token was consumed successfully'),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='user',
            field=models.ForeignKey(help_text='User requesting password reset', on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='passwordresetrequest',
            index=models.Index(fields=['user'], name='password_reset_user_idx'),
        ),
    ]
