# Generated by Django 5.2.8 on 2026-01-11 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_historicalpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='current_address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='historicaladdress',
            name='current_address',
        ),
        migrations.RemoveField(
            model_name='historicaladdress',
            name='permanent_address',
        ),
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.TextField(blank=True, help_text='Full address text', null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Employee or Member owning this address', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaladdress',
            name='address',
            field=models.TextField(blank=True, help_text='Full address text', null=True),
        ),
        migrations.AddField(
            model_name='historicaladdress',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Employee or Member owning this address', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('CURRENT', 'Current Address'), ('PERMANENT', 'Permanent Address')], help_text='Informational address type', max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='address_type',
            field=models.CharField(choices=[('CURRENT', 'Current Address'), ('PERMANENT', 'Permanent Address')], help_text='Informational address type', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('owner',), name='one_active_address_per_owner'),
        ),
    ]
