# Generated by Django 5.2.8 on 2026-01-11 13:10
from django.db import migrations


def backfill_address_owner(apps, schema_editor):
    Address = apps.get_model("users", "Address")

    # Step 1: resolve owner for all rows (without saving yet)
    owner_map = {}

    for addr in Address.objects.all():

        if addr.owner_id:
            owner_map.setdefault(addr.owner_id, []).append(addr)
            continue

        owner = None

        # Employee → owner
        try:
            employees = addr.employees.all()
            if employees.exists():
                owner = employees.first()
        except Exception:
            pass

        # Member → employee → owner
        if owner is None:
            try:
                members = addr.members.select_related("employee")
                if members.exists() and members.first().employee_id:
                    owner = members.first().employee
            except Exception:
                pass

        if owner:
            addr.owner = owner
            owner_map.setdefault(owner.id, []).append(addr)

    # Step 2: enforce single active address per owner
    for owner_id, addresses in owner_map.items():

        # Sort newest first (safe heuristic)
        addresses.sort(
            key=lambda a: (a.updated_at or a.created_at or 0),
            reverse=True,
        )

        # Keep first active, deactivate rest
        for i, addr in enumerate(addresses):
            if i == 0:
                addr.is_active = True
            else:
                addr.is_active = False

            addr.save(update_fields=["owner", "is_active"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_remove_address_current_address_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_address_owner),
    ]
