# Generated by Django 5.2.8 on 2026-01-11 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_deactivate_orphan_addresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.TextField(default='UNKNOWN ADDRESS (legacy)', help_text='Full address text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='owner',
            field=models.ForeignKey(default=1, help_text='Employee or Member owning this address', on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='address',
            field=models.TextField(default='UNKNOWN ADDRESS (legacy)', help_text='Full address text'),
            preserve_default=False,
        ),
    ]
