# Generated by Django 4.2.11 on 2026-01-20 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_alter_address_address_alter_address_owner_and_more"),        
    ]

    operations = [
        # Intentionally empty.
        #
        # This migration freezes the users app schema.
        # Models were relocated to teamcentral and helpdesk,
        # but underlying tables are preserved intentionally.
    ]
