# Generated by Django 4.2.11 on 2026-01-17 09:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the audited action occurred.')),
                ('action', models.CharField(db_index=True, help_text='Canonical action name (e.g. create, update, delete, login).', max_length=64)),
                ('actor_id', models.CharField(blank=True, db_index=True, help_text='Identifier of the actor (user id, service id, etc.).', max_length=64, null=True)),
                ('actor_type', models.CharField(blank=True, help_text='Type of actor (user, system, service).', max_length=32, null=True)),
                ('actor_label', models.CharField(blank=True, help_text='Human-readable actor identifier (email, username).', max_length=255, null=True)),
                ('target_type', models.CharField(blank=True, db_index=True, help_text='Type of entity affected (invoice, client, member, etc.).', max_length=64, null=True)),
                ('target_id', models.CharField(blank=True, db_index=True, help_text='Identifier of the affected entity.', max_length=64, null=True)),
                ('target_label', models.CharField(blank=True, help_text='Human-readable target identifier.', max_length=255, null=True)),
                ('request_id', models.CharField(blank=True, db_index=True, help_text='Request ID for correlating distributed actions.', max_length=64, null=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, help_text='Client IP address, if available.', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string, if available.', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary structured metadata relevant to the event.')),
                ('is_system_event', models.BooleanField(default=False, help_text='True if generated by system/middleware rather than a user.')),
            ],
            options={
                'db_table': 'audit_event',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['action', 'occurred_at'], name='audit_event_action_01e02e_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_event_target__92b051_idx')],
            },
        ),
    ]
