# Generated by Django 4.2.11 on 2026-01-17 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditevent',
            options={'managed': True, 'ordering': ['-occurred_at']},
        ),
    ]
